# Arquivo de configuração do Render (Blueprint) - VERSÃO CORRIGIDA

services:
  # Serviço 1: A sua aplicação Node.js (a vendedora Laura)
  - type: web
    name: laura-chatbot-app
    env: node
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-laura-chatbot
          # CORREÇÃO 1: Trocado 'internalUrl' por 'connectionString'
          property: connectionString
      # Suas outras variáveis de ambiente (adicione os valores no site do Render)
      - key: PAGE_ACCESS_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: PROMPT_BASE
        sync: false
      - key: PROMPT_INTRO
        sync: false
      - key: VERIFY_TOKEN
        sync: false

  # Serviço 2: O banco de dados Redis para armazenar o histórico
  - type: redis
    name: redis-laura-chatbot
    plan: free
    # CORREÇÃO 2: Adicionada a lista de permissões de IP
    ipAllowList:
      - source: 0.0.0.0/0
        description: "Permitir acesso de qualquer lugar"
